snapshot_create_request_body: {
    type: gcs,
    settings: {
      bucket: "{{ gcs_management_bucket_name }}",
      base_path: "{{ es_gcs_backup_folder_name }}/{{ snapshot_base_path }}_{{ base_path_date }}"
    }
}

# Override these values
es_snapshot_host: "{{ ansible_host }}"
snapshot_base_path: "default"
es_gcs_backup_folder_name: "elasticsearch-snapshots-{{ es_snapshot_host }}"