apiVersion: v1
kind: ConfigMap
metadata:
  name: supporttool-server-env
  namespace: {{ .Values.namespace }}
data:
  .env: |
{{ .Values.supporttoolserverenv | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: supporttool-react-env
  namespace: {{ .Values.namespace }}
data:
  env.json: |
{{ .Values.supporttoolreactenv | indent 4 }}
