apiVersion: v1
kind: ConfigMap
metadata:
  name: mentoring-service-environmentjs
  namespace: {{ .Values.namespace }}
data:
  .env: |
{{ .Values.environmentjs | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mentoring-service-configjson
  namespace: {{ .Values.namespace }}
data:
  config.json: |
{{ .Values.configjson | indent 4 }}
