- hosts: es
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  tasks:
    - name: Registering node name
      set_fact:
        es_instance_name: "{% for servername in play_hosts %}{% if inventory_hostname==servername %}es-{{ loop.index }}{% endif %}{% endfor %}"
  roles:
    - elasticsearch-config-update
      
  tags:
    - es