- hosts: postgresql-master
  become: yes
  vars:
    # Ref: https://github.com/geerlingguy/ansible-role-postgresql/issues/136
    postgresql_global_config_options:
    - option: listen_addresses
      value: "{{ ansible_default_ipv4.address }}"
    - option: max_connections
      value: 9999
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - postgresql-config-update
  tags:
    - postgresqlconfigupdate

  
  post_tasks:
    - name: Stop PostgreSQL
      command: /etc/init.d/postgresql stop

    - name: Start PostgreSQL
      command: /etc/init.d/postgresql start