---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    app: {{ .Values.serviceMonitorLabels.release }}
    release: {{ .Values.serviceMonitorLabels.release }}
  name: {{ include "kafka-topic-exporter.fullname" . }}-alertrule
  namespace: {{ default .Values.namespace .Release.Namespace  }}
spec:
  groups:
    
  - name: alertrules.appes
    rules:
    - alert: cassandra RangeScan Latency alert
      annotations:
        message: Cassandra Range Latency has reached 500ms. Please investigate.
        summary: cassandra Range scan latency is Critical
      expr: cassandra_stats{name="org:apache:cassandra:metrics:table:rangelatency:99thpercentile"}
        > 500000
      for: 5m
      labels:
        severity: fatal
          
