---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cb-download-proxy-access-keys
  namespace: {{ .Values.namespace }}
data:
  report-download-key.pem: |
{{ .Values.cbdownloadproxypubkey | indent 4 }}

  report-download-private-key.pem: |
{{ .Values.cbdownloadproxyprivkey | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dl-nginx-conf
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
{{ .Values.dlnginxconf | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dl-edge-conf
  namespace: {{ .Values.namespace }}
data:
  edge.conf: |
{{ .Values.dledgeconf | indent 4 }}

