---
# vars file for deploy-lex-core-service

# For script
release_name: "{{ network_alias_cb_service_registry }}"
template_compose_file_name: cb-service-registry.j2
template_env_file_name: cb-service-registry-env.j2
compose_file_name: "{{ service_cb_service_registry }}.yml"
env_file_name: "{{ service_cb_service_registry }}.env"
helm_env_file_location: "../helm_charts/igot-deploy/templates/"
helm_env_file_name: "{{ helm_env_file_location }}/{{ service_cb_service_registry }}.env"
#chart_path: "../kubernetes-deploy/cb-service-registry"

env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
user_friendly_name: content validation service

# For service
application_port: "{{ service_cb_service_registry_port }}"
image_name: "{{ image_cb_service_registry_service }}"
tag: "{{ tags_cb_service_registry }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_cb_service_registry }}"
reserved_memory: "{{ service_mem_reserved_cb_service_registry }}"
limited_memory: "{{ service_mem_limit_cb_service_registry }}"
#limited_memory: 2048M
health_check_endpoint: http://127.0.0.1:{{ docker_port }}/contentValidation/actuator/health
network_alias_name: "{{ network_alias_cb_service_registry }}"
docker_service_stack_name: lms
docker_service_name: "{{ service_cb_service_registry }}"
force_reload: "{{ force_reload_cb_service_registry }}"
