apiVersion: v1
kind: ConfigMap
metadata:
  name: itsmgeminicredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gcp_gemini_credentials.json: |
{{ .Values.itsmgeminicredentialsjson | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: itsmgcpcredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gcp_gemini_credentials.json: |
{{ .Values.itsmgcpcredentialsjson | indent 4 }}
