apiVersion: v1
kind: ConfigMap
metadata:
  name: itsmgeminicredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gemini_api.json: |
{{ .Values.itsmgeminicredentialsjson | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: itsmgcpcredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gcp-sa.json: |
{{ .Values.itsmgcpcredentialsjson | indent 4 }}
