apiVersion: v1
kind: ConfigMap
metadata:
  name: gcpaiassessmentcredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gcpaiassessmentcredentials.json: |
{{ .Values.gcpaiassessmentcredentialsjson | indent 4 }}
