config:
  modules:
    tcp_connect:
      prober: tcp
      timeout: 5s

{% if monitoring_workload_node_selector %}
nodeSelector: {{ monitoring_workload_node_selector | to_json }}
{% endif %}
{% if monitoring_workload_tolerations %}
tolerations: {{ monitoring_workload_tolerations | to_json }}
{% endif %}
