es:
  uri: "http://{{ groups['es-1'][0] }}:9200"
serviceMonitor:
  enabled: true
  #  namespace: monitoring
  labels: # labels with which the prometheus choose the serviceMonitor
    app: monitoring
    release: prometheus-operator
  interval: 60s
  scrapeTimeout: 30s
  scheme: http

{% if monitoring_workload_node_selector %}
nodeSelector: {{ monitoring_workload_node_selector | to_json }}
{% endif %}
{% if monitoring_workload_tolerations %}
tolerations: {{ monitoring_workload_tolerations | to_json }}
{% endif %}
