{
 "title": "API Manager",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "api",
    "query": "label_values(kong_request_count,api)"
   }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_count{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "sum(rate(kong_request_count{api=~\"${api}\"}[1m]))",
     "legendFormat": "Total Across All API's"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_request_count{api =~ \"$api\"}[$__range])) by (api)",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "sum(increase(kong_request_count{api =~ \"$api\"}[$__range]))",
     "legendFormat": "Total Across All API's"
    }
   ]
  },
  { "title": "Success / Error %", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_request_status_count{api=~\"${api}\",status_code=~\"2..|3..\", status_code!= \"total\"}[1m])) by (api, status_code) / ignoring(api, status_code) group_left sum(increase(kong_request_status_count{api=~\"${api}\", status_code!= \"total\"}[1m]))",
     "legendFormat": "{{api}}-{{status_code}}"
    },
    {
     "expr": "sum(sum(increase(kong_request_status_count{api=~\"${api}\",status_code=~\"2..|3..\", status_code!= \"total\"}[1m])) by (api, status_code) / ignoring(api, status_code) group_left sum(increase(kong_request_status_count{api=~\"${api}\", status_code!= \"total\"}[1m])))",
     "legendFormat": "Total Across All API's"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_request_status_count{api=~\"${api}\",status_code!~\"2..|3..|total\"}[1m])) by (api, status_code) / ignoring(api, status_code) group_left  sum(increase(kong_request_status_count{api=~\"${api}\", status_code!= \"total\"}[1m]))",
     "legendFormat": "{{api}}-{{status_code}}"
    },
    {
     "expr": "sum(sum(increase(kong_request_status_count{api=~\"${api}\",status_code!~\"2..|3..|total\"}[1m])) by (api, status_code) / ignoring(api, status_code) group_left  sum(increase(kong_request_status_count{api=~\"${api}\", status_code!= \"total\"}[1m])))",
     "legendFormat": "Total Across All API's"
    }
   ]
  },
  { "title": "Latency - Average", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Average Total Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_latency_time_sum{api=~\"${api}\"}[1m])) by (api) / sum(rate(kong_latency_time_count{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Average Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_upstream_latency_time_sum{api=~\"${api}\"}[1m])) by (api)  / sum(rate(kong_upstream_latency_time_count{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Success / Error Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Success Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_request_status_count{api=~\"${api}\",status_code=~\"2..|3..\", status_code!= \"total\"}[1m])) by (api, status_code)",
     "legendFormat": "{{api}}-{{status_code}}"
    },
    {
     "expr": "sum(increase(kong_request_status_count{api=~\"${api}\",status_code=~\"2..|3..\", status_code!= \"total\"}[1m]))",
     "legendFormat": "Total Across All API's"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kong_request_status_count{api=~\"${api}\",status_code!~\"2..|3..|total\"}[1m])) by (api, status_code)",
     "legendFormat": "{{api}}-{{status_code}}"
    },
    {
     "expr": "sum(increase(kong_request_status_count{api=~\"${api}\",status_code!~\"2..|3..|total\"}[1m]))",
     "legendFormat": "Total Across All API's"
    }
   ]
  },
  { "title": "Latency Percentile - 99", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Latency - 99 Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p99-{{api}}"
    }
   ]
  },
  {
   "title": "Upstream Latency - 99 Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p99-{{api}}"
    }
   ]
  },
  { "title": "Latency Percentile - 95", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Total Latency - 95 Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p95-{{api}}"
    }
   ]
  },
  {
   "title": "Upstream Latency - 95 Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p95-{{api}}"
    }
   ]
  },
  { "title": "Latency Percentile - 50", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Total Latency - 50 Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(kong_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p50-{{api}}"
    }
   ]
  },
  {
   "title": "Upstream Latency - 50 Percentile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(kong_upstream_latency_time_bucket{api=~\"${api}\"}[1m])) by (api,le))",
     "legendFormat": "p50-{{api}}"
    }
   ]
  },
  {
   "title": "Request / Response Size - Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 }
  },
  {
   "title": "Average Request Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_size_sum{api=~\"${api}\"}[1m])) by (api) / sum(rate(kong_request_size_count{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Average Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_response_size_sum{api=~\"${api}\"}[1m])) by (api) / sum(rate(kong_response_size_count{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Request / Response Size - Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 }
  },
  {
   "title": "Total Request Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_size_sum{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Total Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_response_size_sum{api=~\"${api}\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Apdex Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Apdex Score (Threshold of 500ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_latency_time_bucket{api=~\"${api}\", le=\"0.5\"}[1m])) by (api) / sum(rate(kong_latency_time_count[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  }
 ]
}