{
 "title": "Uptime Kuma - SLA/Latency/Certs Copy",
 "description": "A dashboard to visualize the metrics from HTTP endpoints in [Uptime Kuma](https://github.com/louislam/uptime-kuma)\r\n\r\nImproved by https://github.com/EliottGoye",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "type",
    "query": "label_values(monitor_response_time, monitor_type)"
   },
   {
    "name": "monitor",
    "query": "label_values(monitor_status, monitor_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(monitor_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Online Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(monitor_status == 1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Offline Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(monitor_status == 0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average response time (15m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time (2h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[2h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time (24h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (monitor_name) (\n  avg_over_time(monitor_status{monitor_name=~\"$monitor\"}[5m]) * 100\n)",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  }
 ]
}