{
 "title": "KPI Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Traffic : Requests / Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{cache_status!~\"MISS|NONE\"}[5m]))",
     "legendFormat": "Cached Response"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total[5m])) - sum(rate(nginx_http_requests_total{cache_status!~\"MISS|NONE\"}[5m]))",
     "legendFormat": "Not Cached Response"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{ status=\"444\"}[5m]))",
     "legendFormat": "Blocked Requests outside india"
    }
   ]
  },
  {
   "title": "Top 30 API's req/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_count{api=~\"(faqAssistantGetConfig|updateContentState|listCourseEnrollmentDetails|readContentState|assessmentSubmit|searchUserPrivate|telemetry|listCourseEnrollmentsV4|readContentV2|unReadNotificationCount|getUserProfile|getSystemSettings|workflowGetUserWFApplicationFieldsV2|ratingAndReviews|privateSuperUserUpdate|listCourseEnrollmentSummary|courseAutoenrollment|retakeAssessment|readOrg|playerQuestionListV4|cbPlanListByUser|callExternalApi|userFeed|playerQuSetReadHierarchyV4|userInsights|fetchRequestedReceivedConnection|assessmentSubmitV4|commentTreeGet|commentV3Search)\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "sum(rate(kong_request_count{api=~\"(faqAssistantGetConfig|updateContentState|listCourseEnrollmentDetails|readContentState|assessmentSubmit|searchUserPrivate|telemetry|listCourseEnrollmentsV4|readContentV2|unReadNotificationCount|getUserProfile|getSystemSettings|workflowGetUserWFApplicationFieldsV2|ratingAndReviews|privateSuperUserUpdate|listCourseEnrollmentSummary|courseAutoenrollment|retakeAssessment|readOrg|playerQuestionListV4|cbPlanListByUser|callExternalApi|userFeed|playerQuSetReadHierarchyV4|userInsights|fetchRequestedReceivedConnection|assessmentSubmitV4|commentTreeGet|commentV3Search)\"}[1m]))",
     "legendFormat": "Total Across All API's"
    }
   ]
  },
  {
   "title": "Nodes CPU > 60% Util",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(\n  100 * (\n    1 - (\n      sum by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\n      /\n      sum by (instance) (rate(node_cpu_seconds_total[5m]))\n    )\n  )\n)\n* on(instance) group_left(nodename)\nnode_uname_info{job=\"vm-node-exporter\"}\n> 50",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Nodes RAM > 60% Util",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - (\n    node_memory_MemAvailable_bytes{job=\"vm-node-exporter\"}\n    /\n    node_memory_MemTotal_bytes{job=\"vm-node-exporter\"}\n  )) * 100\n)\n* on(instance) group_left(nodename)\nnode_uname_info{job=\"vm-node-exporter\"}\n> 60",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Pods CPU > 60% Util",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    sum by (namespace, pod) (\n      rate(container_cpu_usage_seconds_total{\n        container!=\"\",\n        image!=\"\",\n        namespace=~\"prod\"\n      }[5m])\n    )\n    /\n    sum by (namespace, pod) (\n      kube_pod_container_resource_requests{\n        resource=\"cpu\",\n        unit=\"core\",\n        namespace=~\"prod\"\n      }\n    )\n  ) * 100\n)\nand\n(\n  (\n    sum by (namespace, pod) (\n      rate(container_cpu_usage_seconds_total{\n        container!=\"\",\n        image!=\"\",\n        namespace=~\"prod\"\n      }[5m])\n    )\n    /\n    sum by (namespace, pod) (\n      kube_pod_container_resource_requests{\n        resource=\"cpu\",\n        unit=\"core\",\n        namespace=~\"prod\"\n      }\n    )\n  ) * 100 > 60\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage > 60% Util",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    sum by (namespace, pod) (\n      container_memory_working_set_bytes{\n        container!=\"\",\n        image!=\"\",\n        namespace=~\"prod\"\n      }\n    )\n    /\n    sum by (namespace, pod) (\n      kube_pod_container_resource_requests{\n        resource=\"memory\",\n        unit=\"byte\",\n        namespace=~\"prod\"\n      }\n    )\n  ) * 100\n)\nand\n(\n  (\n    sum by (namespace, pod) (\n      container_memory_working_set_bytes{\n        container!=\"\",\n        image!=\"\",\n        namespace=~\"prod\"\n      }\n    )\n    /\n    sum by (namespace, pod) (\n      kube_pod_container_resource_requests{\n        resource=\"memory\",\n        unit=\"byte\",\n        namespace=~\"prod\"\n      }\n    )\n  ) * 100 > 60\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Monitoring Alerts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (alertname, severity) (\n  ALERTS{\n    severity=~\"critical|fatal\",\n    alertname!=\"ISR_not_equal_to_partition\"\n  }\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}