{
 "title": "KPI One Dashboard",
 "tags": [
  "info",
  "KPI"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "Deployment Type",
    "query": "label_values(deployment_info, type)"
   },
   {
    "name": "uptime",
    "query": "label_values(monitor_status, monitor_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Portals Uptime",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(\n  clamp_max(\n    avg by (monitor_name) (\n      avg_over_time(\n        monitor_status{monitor_name=~\"iGOT Home|CBP Portal|SPV Portal|MDO Portal|iGOT Portal\"}[$__range]\n      ) * 100\n    ),\n    100\n  ),\n  0.01\n)",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Last 1 Day Avg APIs Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(((sum(increase(nginx_http_requests_total{status=~\"2..|3..|4..\"}[5m])) / sum(increase(nginx_http_requests_total[5m]))) * 100)[1d:5m])",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Last 1 Day Avg API Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(((sum(increase(nginx_http_requests_total{status!~\"2..|3..|4..\"}[5m])) / sum(increase(nginx_http_requests_total[5m]))) * 100)[1d:5m])",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Avg Deployment Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(deployment_success_rate)" }
   ]
  },
  {
   "title": "Requests per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_count{api=~\"(faqAssistantGetConfig|updateContentState|listCourseEnrollmentDetails|readContentState|assessmentSubmit|searchUserPrivate|telemetry|listCourseEnrollmentsV4|readContentV2|unReadNotificationCount|getUserProfile|getSystemSettings|workflowGetUserWFApplicationFieldsV2|ratingAndReviews|privateSuperUserUpdate|listCourseEnrollmentSummary|courseAutoenrollment|retakeAssessment|readOrg|playerQuestionListV4|cbPlanListByUser|callExternalApi|userFeed|playerQuSetReadHierarchyV4|userInsights|fetchRequestedReceivedConnection|assessmentSubmitV4|commentTreeGet|commentV3Search)\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "sum(rate(kong_request_count{api=~\"(faqAssistantGetConfig|updateContentState|listCourseEnrollmentDetails|readContentState|assessmentSubmit|searchUserPrivate|telemetry|listCourseEnrollmentsV4|readContentV2|unReadNotificationCount|getUserProfile|getSystemSettings|workflowGetUserWFApplicationFieldsV2|ratingAndReviews|privateSuperUserUpdate|listCourseEnrollmentSummary|courseAutoenrollment|retakeAssessment|readOrg|playerQuestionListV4|cbPlanListByUser|callExternalApi|userFeed|playerQuSetReadHierarchyV4|userInsights|fetchRequestedReceivedConnection|assessmentSubmitV4|commentTreeGet|commentV3Search)\"}[1m]))",
     "legendFormat": "Total Across All API's"
    }
   ]
  },
  {
   "title": "Success %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{ status!~\"5..\"}[5m])) / sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "Total Success %"
    },
    {
     "expr": "(sum(increase(nginx_http_requests_total{ status!~\"5..\"}[5m])) by (status) / ignoring(status,cache_status) group_left sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "{{status}} {{ cache_status }}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_requests_total{ status!~\"2..|3..|4..\"}[5m]))/  sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "Total Error %"
    },
    {
     "expr": "(sum(increase(nginx_http_requests_total{ status!~\"2..|3..|4..\"}[5m])) by (status) / ignoring(status,cache_status) group_left sum(increase(nginx_http_requests_total[5m]))) * 100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Total Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (api) (\n  rate(kong_latency_time_sum{api=~\"(faqAssistantGetConfig|updateContentState|listCourseEnrollmentDetails|readContentState|assessmentSubmit|searchUserPrivate|telemetry|listCourseEnrollmentsV4|readContentV2|unReadNotificationCount|getUserProfile|getSystemSettings|workflowGetUserWFApplicationFieldsV2|ratingAndReviews|privateSuperUserUpdate|listCourseEnrollmentSummary|courseAutoenrollment|retakeAssessment|readOrg|playerQuestionListV4|cbPlanListByUser|callExternalApi|userFeed|playerQuSetReadHierarchyV4|userInsights|fetchRequestedReceivedConnection|assessmentSubmitV4|commentTreeGet|commentV3Search)\"}[1m])\n)\n/\nsum by (api)(\n  rate(kong_latency_time_count{api=~\"(faqAssistantGetConfig|updateContentState|listCourseEnrollmentDetails|readContentState|assessmentSubmit|searchUserPrivate|telemetry|listCourseEnrollmentsV4|readContentV2|unReadNotificationCount|getUserProfile|getSystemSettings|workflowGetUserWFApplicationFieldsV2|ratingAndReviews|privateSuperUserUpdate|listCourseEnrollmentSummary|courseAutoenrollment|retakeAssessment|readOrg|playerQuestionListV4|cbPlanListByUser|callExternalApi|userFeed|playerQuSetReadHierarchyV4|userInsights|fetchRequestedReceivedConnection|assessmentSubmitV4|commentTreeGet|commentV3Search)\"}[1m])\n)\n",
     "legendFormat": "{{api}}"
    }
   ]
  }
 ]
}