apiVersion: v1
kind: ConfigMap
metadata:
  name: gcpaiassessmentworkercredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gcpaiassessmentworkercredentials.json: |
{{ .Values.gcpaiassessmentworkercredentialsjson | indent 4 }}

---
