FROM vfarcic/jenkins-swarm-agent

ENV ANDROID_SDK_FILENAME=sdk-tools-linux-3859397.zip
ENV ANDROID_SDK_URL=https://dl.google.com/android/repository/${ANDROID_SDK_FILENAME}
ENV ANDROID_API_LEVELS=android-25
ENV ANDROID_BUILD_TOOLS_VERSION=25.0.3
ENV ANDROID_HOME=/opt/android-sdk-linux
ENV PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools/bin

RUN apk update && \
    apk add --no-cache bash unzip wget openjdk8-jre

RUN addgroup -S sunbird && \
    adduser -S -G sunbird -h /home/sunbird sunbird

RUN mkdir -p /opt/jenkins /opt/android-sdk-linux && \
    cd /opt/android-sdk-linux && \
    wget -q ${ANDROID_SDK_URL} && \
    unzip -q ${ANDROID_SDK_FILENAME} && \
    rm -f ${ANDROID_SDK_FILENAME}

RUN yes | ${ANDROID_HOME}/tools/bin/sdkmanager --licenses && \
    ${ANDROID_HOME}/tools/bin/sdkmanager "tools" "platform-tools" && \
    ${ANDROID_HOME}/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" && \
    ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;${ANDROID_API_LEVELS}"

RUN chown -R sunbird:sunbird /opt/android-sdk-linux /opt/jenkins /home/sunbird

USER sunbird
WORKDIR /home/sunbird