apiVersion: v1
kind: ConfigMap
metadata:
  name: gcpdeterministicchatbotcredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gcpdeterministicchatbotcredentials.json: |
{{ .Values.gcpdeterministicchatbotcredentialsjson | indent 4 }}
