apiVersion: v1
kind: ConfigMap
metadata:
  name: gcpdeterministicchatbotcredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gcpdeterministicchatbotcredentials.json: |
{{ .Values.gcpdeterministicchatbotcredentialsjson | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcpdeterministicchatbotstoragecredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gcp_storage_credentials.json: |
{{ .Values.gcpdeterministicchatbotstoragecredentialsjson | indent 4 }}
