apiVersion: v1
kind: ConfigMap
metadata:
  name: aurora-igot-ticketing-servicie-gcpstoragecredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gcp_storage_credentials.json: |
{{ .Values.gcpstoragecredentialsjson | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aurora-igot-ticketing-service-gcpapplicationcredentialsjson
  namespace: {{ .Values.namespace }}
data:
  gcp_application_credentials.json: |
{{ .Values.gcpapplicationcredentialsjson | indent 4 }}

---
