---

- set_fact: base_path_date="{{ lookup('pipe','date +%Y-%m') }}"

- set_fact: snapshot_number="snapshot_{{ lookup('pipe','date +%s') }}"

- name: Create GCS Repository
  uri:
    url: "http://{{ ansible_host }}:9200/_snapshot/{{ snapshot_base_path }}"
    method: PUT
    body: "{{ snapshot_create_request_body | to_json }}"
    headers:
      Content-Type: "application/json"
    timeout: 300